services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    pid: host
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./db/GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb

volumes:
  caddy_data:
  caddy_config: