services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/local/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/app/static
      - caddy_data:/data
      - caddy_config:/config

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    pid: host
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./db/GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb

volumes:
  caddy_data:
  caddy_config: